# Generated by Django 4.0 on 2023-01-13 17:47

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(default='', max_length=30)),
                ('last_name', models.CharField(default='', max_length=30)),
                ('tel', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('added', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('TC', models.BooleanField(default=False)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AppointmentSetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(default='', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(blank=True, default='', max_length=123)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=255)),
                ('last_name', models.CharField(blank=True, default='', max_length=255)),
                ('slug', models.SlugField(blank=True)),
                ('display_photo', models.ImageField(blank=True, upload_to='closers/')),
                ('code', models.CharField(blank=True, default='', max_length=9)),
                ('qrcode', models.ImageField(blank=True, upload_to='user_QRC_auth/')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6)),
                ('category', models.CharField(blank=True, choices=[('Closer', 'Closer'), ('Appointment_setter', 'Appointment_setter')], default='', max_length=25, null=True)),
                ('nationality', django_countries.fields.CountryField(max_length=2)),
                ('city', models.CharField(default='', max_length=100)),
                ('zip_code', models.CharField(default='', max_length=20)),
                ('location', django_countries.fields.CountryField(max_length=2)),
                ('experience', models.CharField(default='', max_length=9)),
                ('resume', models.FileField(default='', upload_to='resumes/')),
                ('document_type', models.FileField(default='', upload_to='extras/')),
                ('education', models.CharField(blank=True, default='', max_length=255)),
                ('work_type', models.CharField(blank=True, choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time')], default='', max_length=25, null=True)),
                ('preferred_niche_to_sell', models.CharField(choices=[('Coaching & Courses', 'Coaching & Courses'), ('Fitness & Suplement', 'Fitness & Suplement'), ('Business & Books', 'Business & Books')], default='', max_length=20)),
                ('hours_available', models.IntegerField(default=0)),
                ('call_per_day', models.IntegerField(blank=True, default=0)),
                ('outbound_calls_per_day', models.IntegerField(default=0)),
                ('appointments_per_day', models.IntegerField(default=0)),
                ('income_per_month', models.IntegerField(blank=True, default=0)),
                ('ticket_size', models.IntegerField(default=0)),
                ('highest_tickets', models.IntegerField(default=0)),
                ('highest_ticket_product', models.CharField(blank=True, default='', max_length=100)),
                ('total_revenue_sales_career', models.IntegerField(default=0)),
                ('total_revenue_sales_three_yrs', models.IntegerField(default=0)),
                ('generated_revenue', models.IntegerField(default=0)),
                ('pay', models.CharField(blank=True, choices=[('Hourly', 'Hourly'), ('Commission', 'Commission')], default='', max_length=10)),
                ('expected_commission', models.IntegerField(blank=True, default=0)),
                ('expected_hourly_pay', models.IntegerField(blank=True, default=0)),
                ('Why_are_you_interested_in_remote_sales', models.TextField(blank=True, default='', max_length=500)),
                ('deal_breaker_for_you', models.TextField(blank=True, default='', max_length=500)),
                ('What_offers_worked_on', models.TextField(blank=True, default='', max_length=500)),
                ('what_niche', models.CharField(blank=True, default='', max_length=100)),
                ('are_you_comfortable_with_commission_based_pay', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255)),
                ('past_trainings', models.CharField(blank=True, default='', max_length=300)),
                ('past_leade_gen', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255)),
                ('why', models.TextField(blank=True, default='', max_length=500)),
                ('offers_worked_on_niche_and_ticket_price', models.CharField(blank=True, default='', max_length=300)),
                ('offers_worked_on_past_years', models.CharField(blank=True, default='', max_length=300)),
                ('reason_for_leaving_last_position', models.TextField(blank=True, default='', max_length=500)),
                ('how_does_a_sales_fit_your_goals', models.TextField(blank=True, default='', max_length=500)),
                ('average_units_sold', models.IntegerField(default=0)),
                ('average_tickets_sold', models.IntegerField(blank=True, default=0)),
                ('timezone', models.CharField(blank=True, default='', max_length=100)),
                ('profile_video', models.FileField(blank=True, default='', upload_to='profile_videos/')),
                ('cover_letter', models.TextField(blank=True, default='', max_length=500)),
                ('achievements', models.TextField(blank=True, default='', max_length=500)),
                ('anything_else_important_to_you_that_we_should_know', models.TextField(blank=True, default='', max_length=500)),
                ('verified', models.BooleanField(default=False)),
                ('start_date', models.CharField(choices=[('I am Ready To Start Now!', 'I am Ready To Start Now!'), ('I will be working In 1 Month', 'I will be working In 1 Month'), ('I will be working In 2 Month', 'I will be working In 2 Month')], default='', max_length=123)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('days_available', models.ManyToManyField(blank=True, to='auths.Days')),
                ('language', models.ManyToManyField(blank=True, to='auths.Language')),
                ('skills', models.ManyToManyField(blank=True, to='auths.Skills')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auths.user')),
            ],
        ),
    ]
