# Generated by Django 4.0 on 2022-12-23 21:23

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_user_nationality_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='added',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nationality',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
