# Generated by Django 4.0 on 2022-12-26 22:38

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0003_user_added_alter_user_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tel',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=9)),
                ('qrcode', models.ImageField(blank=True, upload_to='user_QRC_auth/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auths.user')),
            ],
        ),
    ]
